updated

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,10 +3,20 @@ stages:
   - release
 
 flexapp_testing:
-  stage: build
-  image: ubuntu:24.04
+  stage: .pre
+  image: docker:27.4.1-dind
+  variables:
+    DOCKER_TLS_CERTDIR: ""
+    DOCKER_HOST: tcp://docker:2375/
+  services:
+    - name: docker:27.4.1-dind
+      alias: docker
   rules:
+    - if: $CI_COMMIT_TAG =~ /^release-.*/
     - if: '$CI_COMMIT_BRANCH == "main"'
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+  before_script:
+    - until docker info; do sleep 1; done
   script:
     - echo "Testing the project..."
     - apk update
@@ -26,8 +36,9 @@ flexapp_build_linux:
     - name: docker:27.4.1-dind
       alias: docker
   rules:
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^flexapp-v/'
+    - if: $CI_COMMIT_TAG =~ /^release-.*/
+    - if: '$CI_COMMIT_BRANCH == "main"'
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
   before_script:
     - until docker info; do sleep 1; done
   script:
@@ -52,8 +63,9 @@ flexapp_build_windows:
     - name: docker:27.4.1-dind
       alias: docker
   rules:
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^flexapp-v/'
+    - if: $CI_COMMIT_TAG =~ /^release-.*/
+    - if: '$CI_COMMIT_BRANCH == "main"'
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
   before_script:
     - until docker info; do sleep 1; done
   script:
@@ -68,24 +80,155 @@ flexapp_build_windows:
     paths:
       - exe/flexapp.exe
 
-flexapp_upload_package:
-  stage: .post
-  image: curlimages/curl:latest
-  rules:
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^flexapp-v/'
-  script:
-    - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/flexapp "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp"'
-    - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/flexapp.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp.exe"'
+# flexapp_upload_package:
+#   stage: .post
+#   image: curlimages/curl:latest
+#   rules:
+#     - if: $CI_COMMIT_TAG =~ /^release-.*/
+#     - if: '$CI_COMMIT_BRANCH == "main"'
+#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+#   script:
+#     - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/flexapp "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp"'
+#     - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/flexapp.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp.exe"'
 
-flexapp_release_job:
+# flexapp_release_job:
+#   stage: .post
+#   image: curlimages/curl:latest
+#   rules:
+#     - if: $CI_COMMIT_TAG =~ /^release-.*/
+#     - if: '$CI_COMMIT_BRANCH == "main"'
+#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+#   script: |
+#     echo "Creating a release..."
+#     curl -k --header 'Content-Type: application/json' --header "JOB-TOKEN: $CI_JOB_TOKEN" \
+#      --data "{ \"name\": \"Release $CI_COMMIT_TAG\", \"tag_name\": \"$CI_COMMIT_TAG\", \"ref\": \"$CI_COMMIT_SHA\", \"description\": \"Release for tag $CI_COMMIT_TAG\", \"assets\": { \"links\": [{ \"name\": \"flexapp\", \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp\" },{ \"name\": \"flexapp.exe\", \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp.exe\" }] } }" \
+#      --request POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
+
+flexapp_create_release:
   stage: .post
-  image: curlimages/curl:latest
+  image: ubuntu:latest
+  variables:
+    TRIGGER_TAG: $CI_COMMIT_REF_NAME
+    TRIGGER_TAG_NAME: $CI_COMMIT_REF_NAME
+    IS_DRY_RUN: "false"
+    IS_DRAFT_RELEASE: "false"
+    GIT_USERNAME: "hamm1"
+    GIT_EMAIL: "mlhambright1@gmail.com"
+    RELEASE_TAG: ""
+    GITLAB_TOKEN: $GITLAB_TOKEN
   rules:
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/'
-    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^flexapp-v/'
-  script: |
-    echo "Creating a release..."
-    curl -k --header 'Content-Type: application/json' --header "JOB-TOKEN: $CI_JOB_TOKEN" \
-     --data "{ \"name\": \"Release $CI_COMMIT_TAG\", \"tag_name\": \"$CI_COMMIT_TAG\", \"ref\": \"$CI_COMMIT_SHA\", \"description\": \"Release for tag $CI_COMMIT_TAG\", \"assets\": { \"links\": [{ \"name\": \"flexapp\", \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp\" },{ \"name\": \"flexapp.exe\", \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${CI_COMMIT_TAG}/flexapp.exe\" }] } }" \
-     --request POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
+    - if: $CI_COMMIT_BRANCH == "main"
+      changes:
+        - RELEASE_NOTES.md
+    - if: $CI_COMMIT_TAG =~ /^release-.*/
+    - if: '$CI_COMMIT_BRANCH == "main"'
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+  before_script:
+    - apt-get update -qq && apt-get install -y -qq git curl jq
+    - git config --global user.email "${GIT_EMAIL}"
+    - git config --global user.name "${GIT_USERNAME}"
+    - git remote set-url origin https://${GIT_USERNAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
+  script:
+    - set -ue
+    - git config --global http.sslVerify false
+    - |
+      set -xue
+      if [[ "${CI_COMMIT_REF_NAME}" == release-* ]]; then
+        echo "Triggered by tag push: ${CI_COMMIT_REF_NAME}"
+        # For tag pushes, remove the "release-" prefix.
+        RELEASE_TAG="${CI_COMMIT_REF_NAME#release-}"
+      else
+        echo "Triggered by main push with changes to RELEASE_NOTES.md"
+        # Compute the new version by incrementing the patch of the latest published tag (vX.Y.Z)
+        git fetch --tags
+        latest_tag=$(git tag --list "v[0-9]*.[0-9]*.[0-9]*" | sort -V | tail -n 1)
+        echo "Latest published tag is: $latest_tag"
+        if [ -z "$latest_tag" ]; then
+          new_version="0.0.1"
+        else
+          version=${latest_tag#v}
+          IFS='.' read -r major minor patch <<< "$version"
+          patch=$((patch + 1))
+          new_version="${major}.${minor}.${patch}"
+        fi
+        # The published release tag should be prefixed with "v"
+        RELEASE_TAG="v${new_version}"
+      fi
+
+      # Determine if this is a pre-release (if the tag ends with -rcN)
+      IS_PRE_RELEASE=false
+      if echo "${RELEASE_TAG}" | grep -E -- '-rc[0-9]+$'; then
+        IS_PRE_RELEASE=true
+      fi
+
+      # Verify that the release tag does not already exist.
+      if [[ -n $(git tag -l | grep -E -- '^'${RELEASE_TAG}) ]]; then
+        echo "ERROR: Release tag ${RELEASE_TAG} already exists in repository. Refusing to continue."
+        exit 1
+      fi
+
+      # Export the variables for subsequent steps.
+      echo "RELEASE_TAG=${RELEASE_TAG}" >> release.env
+      echo "IS_PRE_RELEASE=${IS_PRE_RELEASE}" >> release.env
+      source release.env
+    
+    # Creating the release tag
+    - |
+      set -ue
+      if [[ "$IS_DRY_RUN" == "true" ]]; then
+        echo "IS_DRY_RUN=${IS_DRY_RUN}"
+        exit 0
+      fi
+      echo "Creating release tag ${RELEASE_TAG}"
+      git tag ${RELEASE_TAG}
+      git push origin ${RELEASE_TAG}
+    
+    # Deleting pushed tag (only if triggered by tag push)
+    - |
+      if [[ "${CI_COMMIT_REF_NAME}" == release-* ]]; then
+        set -ue
+        echo "Deleting pushed tag ${TRIGGER_TAG_NAME}"
+        git tag -d ${TRIGGER_TAG_NAME}
+        git push -d origin ${TRIGGER_TAG_NAME}
+      fi
+    
+    # Upload Binaries
+    - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/flexapp "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${RELEASE_TAG}/flexapp"'
+    - 'curl -k --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file exe/flexapp.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${RELEASE_TAG}/flexapp.exe"'
+
+    # Create Release using GitLab API
+    - |
+      set -ue
+      source release.env
+      
+      # Read release notes
+      RELEASE_NOTES=$(cat RELEASE_NOTES.md)
+      
+      curl -k \
+      --request POST \
+      --header "Content-Type: application/json" \
+      --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
+      --data "{
+        \"name\": \"Release ${RELEASE_TAG}\",
+        \"tag_name\": \"${RELEASE_TAG}\",
+        \"ref\": \"${CI_COMMIT_SHA}\",
+        \"description\": $(echo "$RELEASE_NOTES" | jq -Rs .),
+        \"assets\": {
+          \"links\": [
+            {
+              \"name\": \"flexapp\",
+              \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${RELEASE_TAG}/flexapp\"
+            },
+            {
+              \"name\": \"flexapp.exe\",
+              \"url\": \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flexapp/${RELEASE_TAG}/flexapp.exe\"
+            }
+          ]
+        }
+      }" \
+      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
+  
+  artifacts:
+    reports:
+      dotenv: release.env
+    expire_in: 1 hour
